defaults:
  - _self_
  - agent: baku
  - suite: ur5e_suite
  - dataloader: p3po_xarm
  - override hydra/launcher: submitit_local

# Root Dir
root_dir: /scratch/repos/ref_P3PO
data_dir: /scratch/data/open_teach/
use_p3po: True
training: False
eval_task_name: "put tennis ball in plate"
relative_actions: true
use_dataset_stats_for_action_spec: false
use_quaternion_orientation: false
training_dir: null
use_training_action_spec: true
action_spec_path: null

# misc
seed: 2
device: cuda
save_video: true
save_train_video: false
use_tb: true
batch_size: 64

# experiment
obs_type: "features" # pixels, features
training_keys: ["graph"]
depth_keys: ["depth"]
num_demos_per_task: 50
encoder_type: "resnet" # biase, resnet
policy_type: "gpt" # mlp, gpt
policy_head: deterministic # deterministic, gmm, bet, diffusion, vqbet
use_proprio: false
use_language: false
use_actions: false
eval: true
prompt: text # text, goal, intermediate_goal
experiment: eval
experiment_label: ${policy_head}
run_name: eval

# action chunking
temporal_agg: true # aggregate actions over time
num_queries: 10

# expert dataset
expert_dataset: ${dataloader.bc_dataset}

# Load weights
bc_weight: ${training_dir}/snapshot/600000.pt

hydra:
  run:
    dir: ./exp_local/${run_name}/${now:%m.%d.%H.%M}_${experiment}/
  sweep:
    dir: ./exp_local/${run_name}/${now:%m.%d.%H.%M}
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder: ./exp_local/${run_name}/${now:%m.%d.%H.%M}_${experiment}/.slurm
